POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###
GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njg4OTAxNjYsInN1YiI6IjIyNzUwOGQwLTExNjQtNDg1Ni04OTYwLTkwMDBlODJmODM1ZCJ9.vrLfBCWQkccN4YyYIjkWqDAuaG0QHIiOIPYKEGpfP5o
Content-Type: application/json

### 

GET http://localhost:8000/products/acebe655-6cd8-4f87-bdb4-f3dda3138d67 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/products/acebe655-6cd8-4f87-bdb4-f3dda3138d67 HTTP/1.1
Content-Type: application/json

{
    "name": "My Product Updated",
    "price": 200
}

###
DELETE http://localhost:8000/products/acebe655-6cd8-4f87-bdb4-f3dda3138d67 HTTP/1.1
Content-Type: application/json
